### ISSUE TITLE
the timeline more tidy and compact

### ISSUE THREAD

**Issue by fireflysss** [Canna71/obsidian-chronology#31]
The calendar we made looks great, and the list looks great too
Click on the daily , the hour table is too wide
Can it be more compact

**Comment by grrowl** [comment]
You can use this css snippet (apply under Settings > Appearance) to shrink the view.

```css
.chronology-timeline-container {
    display: flex;
    flex-direction: column;
}
.chrono-temp-slot1 {
    height: auto;
    min-height: 2em;
}
.chrono-cluster-container {
    min-height: 1em;
}
.chrono-cluster-container:empty {
    min-height: unset;
}
```

it's not ideal, there's something funked up with the flexbox styles in the plugin, but this was quick enough to work for me :)
